export const PERMISSIONS = {
  // Students
  STUDENTS_VIEW: "students.view",
  STUDENTS_CREATE: "students.create",
  STUDENTS_EDIT: "students.edit",
  STUDENTS_DELETE: "students.delete",
  STUDENTS_IMPORT: "students.import",

  // Teachers / Staff
  TEACHERS_VIEW: "teachers.view",
  TEACHERS_CREATE: "teachers.create",
  TEACHERS_EDIT: "teachers.edit",
  TEACHERS_DELETE: "teachers.delete",

  // Academics
  ACADEMICS_VIEW: "academics.view",
  CLASSES_MANAGE: "classes.manage",
  SECTIONS_MANAGE: "sections.manage",
  SUBJECTS_MANAGE: "subjects.manage",
  TIMETABLE_VIEW: "timetable.view",
  TIMETABLE_MANAGE: "timetable.manage",

  // Attendance
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_MARK: "attendance.mark",
  ATTENDANCE_EDIT: "attendance.edit",
  ATTENDANCE_APPROVE: "attendance.approve",
  STAFF_ATTENDANCE_VIEW: "staff_attendance.view",
  STAFF_ATTENDANCE_MARK: "staff_attendance.mark",

  // Leaves
  LEAVE_REQUEST: "leave.request",
  LEAVE_VIEW_SELF: "leave.view_self",
  LEAVE_VIEW_ALL: "leave.view_all",
  LEAVE_APPROVE: "leave.approve",

  // Assignments & Exams
  ASSIGNMENTS_VIEW: "assignments.view",
  ASSIGNMENTS_CREATE: "assignments.create",
  ASSIGNMENTS_GRADE: "assignments.grade",
  EXAMS_VIEW: "exams.view",
  EXAMS_MANAGE: "exams.manage",
  MARKS_ENTRY: "marks.entry",
  REPORT_CARDS_GENERATE: "report_cards.generate",

  // Finance & Payroll
  FEES_VIEW: "fees.view",
  FEES_COLLECT: "fees.collect",
  FEES_MANAGE_STRUCTURE: "fees.manage_structure",
  FEES_REMIND: "fees.remind",
  PAYROLL_VIEW: "payroll.view",
  PAYROLL_PROCESS: "payroll.process",
  PAYROLL_APPROVE: "payroll.approve",

  // Operations
  TASKS_VIEW: "tasks.view",
  TASKS_CREATE: "tasks.create",
  TASKS_ASSIGN: "tasks.assign",
  TASKS_MANAGE: "tasks.manage",
  ANNOUNCEMENTS_VIEW: "announcements.view",
  ANNOUNCEMENTS_CREATE: "announcements.create",
  CALENDAR_VIEW: "calendar.view",
  CALENDAR_MANAGE: "calendar.manage",

  // Campus Services
  LIBRARY_MANAGE: "library.manage",
  TRANSPORT_MANAGE: "transport.manage",
  HOSTEL_MANAGE: "hostel.manage",

  // Administration
  REPORTS_VIEW: "reports.view",
  AUDIT_LOGS_VIEW: "audit.view",
  SETTINGS_MANAGE: "settings.manage",
  USERS_MANAGE: "users.manage",
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  PRINCIPAL: [
    PERMISSIONS.STUDENTS_VIEW, PERMISSIONS.STUDENTS_CREATE, PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.TEACHERS_VIEW, PERMISSIONS.TEACHERS_CREATE, PERMISSIONS.TEACHERS_EDIT,
    PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.CLASSES_MANAGE, PERMISSIONS.SECTIONS_MANAGE, PERMISSIONS.SUBJECTS_MANAGE,
    PERMISSIONS.TIMETABLE_VIEW, PERMISSIONS.TIMETABLE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MARK, PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.STAFF_ATTENDANCE_VIEW, PERMISSIONS.LEAVE_VIEW_ALL, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ASSIGNMENTS_VIEW, PERMISSIONS.EXAMS_VIEW, PERMISSIONS.EXAMS_MANAGE, PERMISSIONS.REPORT_CARDS_GENERATE,
    PERMISSIONS.FEES_VIEW, PERMISSIONS.FEES_REMIND,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_ASSIGN, PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_VIEW, PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.LIBRARY_MANAGE, PERMISSIONS.TRANSPORT_MANAGE, PERMISSIONS.HOSTEL_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.AUDIT_LOGS_VIEW, PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.USERS_MANAGE
  ],
  VICE_PRINCIPAL: [
    PERMISSIONS.STUDENTS_VIEW, PERMISSIONS.STUDENTS_CREATE, PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.TEACHERS_VIEW, PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MARK, PERMISSIONS.STAFF_ATTENDANCE_VIEW,
    PERMISSIONS.LEAVE_VIEW_ALL, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ASSIGNMENTS_VIEW, PERMISSIONS.EXAMS_VIEW, PERMISSIONS.EXAMS_MANAGE, PERMISSIONS.REPORT_CARDS_GENERATE,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.ANNOUNCEMENTS_VIEW, PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.REPORTS_VIEW
  ],
  HOD: [
    PERMISSIONS.STUDENTS_VIEW, PERMISSIONS.TEACHERS_VIEW, PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.TIMETABLE_VIEW, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.LEAVE_VIEW_ALL, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.ASSIGNMENTS_VIEW, PERMISSIONS.ASSIGNMENTS_CREATE, PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.EXAMS_VIEW, PERMISSIONS.MARKS_ENTRY,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.CALENDAR_VIEW
  ],
  TEACHER: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.LEAVE_REQUEST, PERMISSIONS.LEAVE_VIEW_SELF,
    PERMISSIONS.ASSIGNMENTS_VIEW, PERMISSIONS.ASSIGNMENTS_CREATE, PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.EXAMS_VIEW, PERMISSIONS.MARKS_ENTRY,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.CALENDAR_VIEW
  ],
  ACCOUNTANT: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FEES_VIEW, PERMISSIONS.FEES_COLLECT, PERMISSIONS.FEES_MANAGE_STRUCTURE, PERMISSIONS.FEES_REMIND,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.ANNOUNCEMENTS_VIEW, PERMISSIONS.CALENDAR_VIEW
  ],
  HR_ADMIN: [
    PERMISSIONS.TEACHERS_VIEW, PERMISSIONS.TEACHERS_CREATE, PERMISSIONS.TEACHERS_EDIT,
    PERMISSIONS.STAFF_ATTENDANCE_VIEW, PERMISSIONS.STAFF_ATTENDANCE_MARK,
    PERMISSIONS.LEAVE_VIEW_ALL, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.ANNOUNCEMENTS_VIEW, PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.REPORTS_VIEW
  ],
  STUDENT: [
    PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ASSIGNMENTS_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.CALENDAR_VIEW
  ],
  PARENT: [
    PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ASSIGNMENTS_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.CALENDAR_VIEW
  ]
};
